-- ============================================================
-- Akshar Studio — FAQs (admin-managed)
-- Run in Supabase → SQL Editor. Replace admin email if different.
-- ============================================================
create table if not exists public.faqs (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  question    text not null,
  answer      text not null,
  category    text default 'General',
  sort_order  integer default 0,
  is_active   boolean default true
);

alter table public.faqs enable row level security;

drop policy if exists "faqs_public_read" on public.faqs;
create policy "faqs_public_read" on public.faqs
  for select using (is_active = true);

drop policy if exists "faqs_admin_all" on public.faqs;
create policy "faqs_admin_all" on public.faqs
  for all to authenticated
  using ((auth.jwt() ->> 'email') = 'sebas.stllioni@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'sebas.stllioni@gmail.com');
