-- ============================================================
-- Ever Yours — abandoned-order capture (order_leads)
-- Run in Supabase: SQL Editor → New query → paste → Run
--
-- WHY: the order form is 3 steps. People who fill step 1 and drop at
-- the address step are warm leads we can chase on WhatsApp — but only
-- if we saved their name + number. This table holds those partials.
--
-- SECURITY MODEL: anon has NO direct access to these tables. The site
-- writes only through the security-definer functions below, which cap
-- field lengths, validate the phone, rate-limit by IP, and never let a
-- row move backwards or re-open after it converted. Reads are admin-only.
-- ============================================================

-- ── Leads ────────────────────────────────────────────────────
create table if not exists public.order_leads (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- Client-generated UUID kept in sessionStorage; lets one visitor keep
  -- updating their own row as they move through the steps.
  session_id       uuid        not null unique,
  customer_name    text,
  customer_phone   text,
  customer_email   text,
  letter_type      text,
  recipient_name   text,
  occasion         text,
  reached_step     integer     not null default 1,
  estimated_total  integer,
  converted        boolean     not null default false,
  status           text        not null default 'new'   -- new | contacted | recovered | dropped
);

alter table public.order_leads enable row level security;

-- No anon policies at all -> the anon key cannot select, insert or update
-- this table directly. All writes go through the functions below.

drop policy if exists "Admin read leads" on public.order_leads;
create policy "Admin read leads" on public.order_leads for select to authenticated
  using ( (auth.jwt() ->> 'email') = 'sebas.stallioni@gmail.com' );

drop policy if exists "Admin update leads" on public.order_leads;
create policy "Admin update leads" on public.order_leads for update to authenticated
  using ( (auth.jwt() ->> 'email') = 'sebas.stallioni@gmail.com' )
  with check ( (auth.jwt() ->> 'email') = 'sebas.stallioni@gmail.com' );

create index if not exists order_leads_open_idx
  on public.order_leads (converted, created_at desc);
create index if not exists order_leads_created_idx
  on public.order_leads (created_at desc);

-- ── Abuse throttle ───────────────────────────────────────────
-- Deliberately a SEPARATE table with no link to order_leads, so a
-- visitor's network identity is never stored alongside their letter.
-- We keep a salted hash, never the raw IP.
create table if not exists public.lead_throttle (
  ip_hash       text primary key,
  window_start  timestamptz not null default now(),
  new_leads     integer     not null default 0,   -- rows created this window
  calls         integer     not null default 0    -- total RPC hits this window
);

alter table public.lead_throttle enable row level security;
-- No policies for anyone. Only the security-definer functions touch it.

-- ── Insert-or-update a partial order, with abuse limits ───────
-- Tunables live at the top of the function body:
--   MAX_NEW_PER_IP    new leads from one IP per hour
--   MAX_CALLS_PER_IP  total RPC calls from one IP per hour
--   MAX_NEW_GLOBAL    new leads site-wide per hour (circuit breaker)
--   IP_SALT           already generated for you; keep it private
-- Raise them if you ever see a legitimate customer throttled.
create or replace function public.upsert_order_lead(
  p_session_id      uuid,
  p_customer_name   text,
  p_customer_phone  text,
  p_customer_email  text,
  p_letter_type     text,
  p_recipient_name  text,
  p_occasion        text,
  p_reached_step    integer,
  p_estimated_total integer
) returns void
language plpgsql
security definer
set search_path = public
as $fn$
declare
  MAX_NEW_PER_IP   constant integer := 10;
  MAX_CALLS_PER_IP constant integer := 60;
  MAX_NEW_GLOBAL   constant integer := 200;
  IP_SALT          constant text    := 'akshar-0683dae2489fa67229e82f3f1329f2d3';

  v_headers text;
  v_ip      text;
  v_hash    text;
  v_new     integer;
  v_calls   integer;
  v_digits  text;
  v_exists  boolean;
begin
  -- ── Validate the phone: it is the whole point of a lead ──
  v_digits := regexp_replace(coalesce(p_customer_phone, ''), '[^0-9]', '', 'g');
  if length(v_digits) < 10 or length(v_digits) > 15 then
    return;
  end if;
  -- reject 0000000000, 9999999999 and friends
  if v_digits ~ '^(.)\1+$' then
    return;
  end if;

  v_exists := exists (select 1 from public.order_leads where session_id = p_session_id);

  -- ── Rate limit by caller IP ──────────────────────────────
  -- PostgREST exposes the request headers; they are absent when the
  -- function is called from the SQL editor. If we cannot identify the
  -- caller we fail OPEN on the per-IP check (so a header change can
  -- never lock out real customers) and rely on the global cap below.
  v_headers := current_setting('request.headers', true);
  if v_headers is not null and v_headers <> '' then
    v_ip := btrim(split_part(coalesce(v_headers::json ->> 'x-forwarded-for', ''), ',', 1));
  end if;

  if coalesce(v_ip, '') <> '' then
    v_hash := md5(v_ip || IP_SALT);

    insert into public.lead_throttle as t (ip_hash, window_start, new_leads, calls)
    values (v_hash, now(), case when v_exists then 0 else 1 end, 1)
    on conflict (ip_hash) do update set
      window_start = case when t.window_start < now() - interval '1 hour'
                          then now() else t.window_start end,
      new_leads    = case when t.window_start < now() - interval '1 hour'
                          then (case when v_exists then 0 else 1 end)
                          else t.new_leads + (case when v_exists then 0 else 1 end) end,
      calls        = case when t.window_start < now() - interval '1 hour'
                          then 1 else t.calls + 1 end
    returning t.new_leads, t.calls into v_new, v_calls;

    if v_calls > MAX_CALLS_PER_IP then return; end if;
    if not v_exists and v_new > MAX_NEW_PER_IP then return; end if;

    -- Opportunistic cleanup so this table stays tiny.
    if random() < 0.01 then
      delete from public.lead_throttle where window_start < now() - interval '1 day';
    end if;
  end if;

  -- ── Global circuit breaker ───────────────────────────────
  if not v_exists then
    if (select count(*) from public.order_leads
         where created_at > now() - interval '1 hour') >= MAX_NEW_GLOBAL then
      return;
    end if;
  end if;

  -- ── Insert or advance the partial order ──────────────────
  insert into public.order_leads as l (
    session_id, customer_name, customer_phone, customer_email,
    letter_type, recipient_name, occasion, reached_step, estimated_total
  ) values (
    p_session_id,
    left(btrim(p_customer_name),  120),
    left(btrim(p_customer_phone),  20),
    left(btrim(p_customer_email), 160),
    left(p_letter_type,            80),
    left(btrim(p_recipient_name), 120),
    left(p_occasion,               80),
    greatest(1, least(3, coalesce(p_reached_step, 1))),
    greatest(0, least(1000000, coalesce(p_estimated_total, 0)))
  )
  on conflict (session_id) do update set
    customer_name   = excluded.customer_name,
    customer_phone  = excluded.customer_phone,
    customer_email  = excluded.customer_email,
    letter_type     = excluded.letter_type,
    recipient_name  = excluded.recipient_name,
    occasion        = excluded.occasion,
    -- progress only ever moves forward
    reached_step    = greatest(l.reached_step, excluded.reached_step),
    estimated_total = excluded.estimated_total,
    updated_at      = now()
  where l.converted = false;   -- a placed order is never re-opened
end;
$fn$;

-- ── Mark a lead converted once the real order lands ────────────
create or replace function public.mark_lead_converted(p_session_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
begin
  update public.order_leads
     set converted = true, status = 'recovered', updated_at = now()
   where session_id = p_session_id;
end;
$fn$;

-- The website (anon key) may only call these two functions.
revoke all on function public.upsert_order_lead(uuid,text,text,text,text,text,text,integer,integer) from public;
revoke all on function public.mark_lead_converted(uuid) from public;
grant execute on function public.upsert_order_lead(uuid,text,text,text,text,text,text,integer,integer) to anon, authenticated;
grant execute on function public.mark_lead_converted(uuid) to anon, authenticated;

-- ============================================================
-- VERIFY (optional) — paste this into the SQL Editor after the
-- migration above to confirm everything works. It cleans up after
-- itself. Note: run from the SQL Editor there is no IP header, so
-- the per-IP limits are skipped here by design — only the phone
-- validation and the global cap are exercised.
-- ============================================================
--
-- -- 1. Both functions exist
-- select proname, pronargs from pg_proc
--  where proname in ('upsert_order_lead', 'mark_lead_converted');
--
-- -- 2. A good lead is stored
-- select public.upsert_order_lead(
--   gen_random_uuid(), 'Test Person', '9843245279', '',
--   'Love Letter', 'Priya', 'Anniversary', 2, 499);
-- select customer_name, customer_phone, reached_step, estimated_total, status
--   from public.order_leads where customer_name = 'Test Person';
--
-- -- 3. Junk phones are silently rejected (count stays 1)
-- select public.upsert_order_lead(gen_random_uuid(), 'Bot', '0000000000', '', 'x','y','z',1,0);
-- select public.upsert_order_lead(gen_random_uuid(), 'Bot', '123',        '', 'x','y','z',1,0);
-- select public.upsert_order_lead(gen_random_uuid(), 'Bot', '',           '', 'x','y','z',1,0);
-- select count(*) as should_be_1 from public.order_leads
--  where customer_name in ('Test Person', 'Bot');
--
-- -- 4. Clean up
-- delete from public.order_leads where customer_name in ('Test Person', 'Bot');
