-- ============================================================
-- Akshar Studio — Reviews (admin-managed customer testimonials)
-- Run in Supabase → SQL Editor. Replace admin email if different.
-- ============================================================
create table if not exists public.reviews (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null,
  location    text,
  rating      integer default 5,
  letter_type text,
  quote       text not null,
  is_active   boolean default true,
  sort_order  integer default 0
);

alter table public.reviews enable row level security;

drop policy if exists "reviews_public_read" on public.reviews;
create policy "reviews_public_read" on public.reviews
  for select using (is_active = true);

drop policy if exists "reviews_admin_all" on public.reviews;
create policy "reviews_admin_all" on public.reviews
  for all to authenticated
  using ((auth.jwt() ->> 'email') = 'sebas.stllioni@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'sebas.stllioni@gmail.com');
